### ISSUE TITLE
My git practical

### ISSUE THREAD

**Issue by muskanlanet** [muskanlanet/Test-git#1]
Please create index.html file and add h1 tag with “My git pratical" and
description

**Comment by Shadowcoder2804** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <h1> My GIT practical </h1>
</body>
</html>

**Comment by muskanlanet** [comment]
<h1>My git practical</h1>
